# TODO: Determine a MSRV and use that here instead
image: antoniosbarotsis/mirte-rs:opencv-ros-py-v5

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

cache:
  key:
    files:
      - Cargo.lock
  paths:
    - .cargo/registry/index
    - .cargo/registry/cache
    - target/debug/deps
    - target/debug/build

stages:
  - build
  - test
  - lint

build:
  stage: build
  script:
    cargo build --all-features

test:
  stage: test
  needs: 
  - build
  script:
    cargo test --verbose

lint:
  stage: lint
  needs: 
  - build
  script:
    - rustup component add clippy rustfmt
    - cargo clippy --all-features -- -D warnings
    - cargo fmt --check
