[package]
name = "rostest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["proc-macro"]

[dependencies]
serial_test  = "2.0.0"
syn = "2.0"
quote = "1.0"
